### ISSUE TITLE
Make game logic stateless

### ISSUE THREAD

**Issue by deadpassive** [cartelgame/cartel#19]
State should be passed in as an argument

**Comment by deadpassive** [comment]
@StevieD666 I'm about to make a branch for this. Basically it's the same logic as you have, but you pass the game state in as an argument to all methods that need it. 

I think we need to do something like  this and make the game logic static, otherwise we'll be creating a new game object for every request.

**Comment by StevieD666** [comment]
@deadpassive, OK sounds good, I am planning to do some more on Sunday, so as long as I can continue all good!

**Comment by deadpassive** [comment]
Have a look at the stateless-game branch. I've created mongoose models for everything and you can now save the game state. It's a bit different to how you laid everything out:
- **GameState** model class stores the current state of the game.
- **TileSet** model class for storing lists of tiles
- **PlayerState** model class stores everything about the player related to the game (merged player and position from your classes)
- A players ownedTiles list now just contains the indices of the tiles they own - I tried using references to mongo objects but much pain was suffered.

I _think_ your logic still works OK. Players move around buying things and their money goes up as they pass go.

At the moment I'm a bit scared to merge the branch as I've made loads of changes...
