### ISSUE TITLE
Create game logic module

### ISSUE THREAD

**Issue by deadpassive** [cartelgame/cartel#7]
Create game logic module and function stubs.

**Comment by StevieD666** [comment]
Not committed yet, but I have basic game code to move around the board and each player receives £200 for passing go.

Partial classes,
Game, Dice, Player, Tile, GameState, Game has two methods -> init and next.

**Comment by StevieD666** [comment]
If I could get bind to work, might be able to refactor the bloody code!

**Comment by StevieD666** [comment]
Now can buy properties for sale, properties are now grouped. Still to do, add an attribute to allow houses/hotels to be purchased when all properties are purchased in a group.

**Comment by deadpassive** [comment]
Check out my recent commit. I've refactored your code into Node modules. I haven't changed any logic, but all classes are not in separate files. For usage check out gametest.js.

I haven't touched your cartel-game.js, so it's there if you want to check I haven't missed anything.

**Comment by deadpassive** [comment]
Once you're happy that I haven't broken anything then I think we can close this issue off and create more smaller ones.

**Comment by StevieD666** [comment]
Seems good to me,

**Comment by deadpassive** [comment]
Awesome.
